version: "3.7"

# services:
#   app:
#     image: fishjoyreact:v1
#     ports:
#       - "5000:80"
#     restart: unless-stopped

services:
  app:
    image: fishjoyreact:v1 
    volumes:
      - ./src:/app/src
    ports:
      - "5000:3000"
    restart: unless-stopped

# services:
#   app:
#     image: nginx:1.17-alpine
#     volumes:
#       - ./build:/usr/share/nginx/html
#     ports:
#       - "5000:80"
#     restart: unless-stopped